#!/bin/bash
set -euo pipefail
export PATH=./node_modules/.bin:$PATH

function test() {
    for f in */*.test.ts; do
        echo "running test on $f"
        start $f
    done
}

function start() {
    sourcefile=$1
    build $1
    run
    clean
}

function build() {
    sourcefile=$1
    esbuild --bundle --platform=node --external:classic-level --sourcemap --outfile=build.js $sourcefile
}

function run() {
    node build.js
}

function clean() {
    rm -rf build.js build.js.map
}

set -x
eval "$@"
