#!/bin/bash
set -euo pipefail
export PATH=./node_modules/.bin:$PATH

function test() {
    for f in */*.test.ts; do
        echo "running test on $f"
        start $f
    done
}

function start() {
    sourcefile=$1
    build $1
    node --enable-source-maps build.js
    clean
}

function start-high-ram() {
    sourcefile=$1
    build $1
    node --max-old-space-size=8192 build.js
    clean
}

function build() {
    sourcefile=$1
    esbuild --bundle --platform=node --external:classic-level --sourcemap --outfile=build.js $sourcefile
}

function clean() {
    rm -rf build.js build.js.map
}

# connect to db:
# sudo -i -u postgres
# psql

set -x
eval "$@"  | tee -a log.log
